import type { GadgetModel } from "gadget-server";

// This file describes the schema for the "shopifyShop" model, go to https://bartesian-mobile-middleware.gadget.app/edit to view/edit your model in Gadget
// For more information on how to update this file http://docs.gadget.dev

export const schema: GadgetModel = {
  type: "gadget/model-schema/v1",
  storageKey: "DataModel-Shopify-Shop",
  fields: {},
  shopify: {
    fields: [
      "address1",
      "address2",
      "alerts",
      "billingAddress",
      "checkoutApiSupported",
      "city",
      "countriesInShippingZones",
      "country",
      "countryCode",
      "countryName",
      "countyTaxes",
      "currency",
      "currencyFormats",
      "customerAccounts",
      "customerAccountsV2",
      "customerEmail",
      "description",
      "domain",
      "eligibleForPayments",
      "email",
      "enabledPresentmentCurrencies",
      "finances",
      "gdprRequests",
      "googleAppsDomain",
      "googleAppsLoginEnabled",
      "hasDiscounts",
      "hasGiftCards",
      "hasStorefront",
      "ianaTimezone",
      "latitude",
      "longitude",
      "marketingSmsContentEnabledAtCheckout",
      "moneyFormat",
      "moneyInEmailsFormat",
      "moneyWithCurrencyFormat",
      "moneyWithCurrencyInEmailsFormat",
      "multiLocationEnabled",
      "myshopifyDomain",
      "name",
      "orderNumberFormatPrefix",
      "orderNumberFormatSuffix",
      "passwordEnabled",
      "phone",
      "plan",
      "planDisplayName",
      "planName",
      "planPublicDisplayName",
      "preLaunchEnabled",
      "primaryLocale",
      "province",
      "provinceCode",
      "requiresExtraPaymentsAgreement",
      "resourceLimits",
      "richTextEditorUrl",
      "setupRequired",
      "shipsToCountries",
      "shopOwner",
      "shopifyCreatedAt",
      "shopifyUpdatedAt",
      "source",
      "syncs",
      "taxShipping",
      "taxesIncluded",
      "timezone",
      "timezoneAbbreviation",
      "timezoneOffset",
      "timezoneOffsetMinutes",
      "transactionalSmsDisabled",
      "unitSystem",
      "url",
      "weightUnit",
      "zipCode",
    ],
  },
};
